POST http://localhost:3001/api/items
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVya2tpRXNpbWVya2tpIiwiZW1haWwiOiJlcmtraS5lc2ltZXJra2lAZ21haWwuY29tIiwiaWQiOiI2M2Q2Yzc2MWQ1NjNjZmFkN2FiYzlkNDQiLCJpYXQiOjE2NzUwNjkzMTZ9.UylPm6Qx6f_g3rnAnsvFLVc4qZPrTjxBcZT8DbpBJQY

{
  "name": "testitem2", "description": "testcription2", "category": "testcategory2", "price": 40
}