GET http://localhost:3001/api/items/myitems
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0ZW1haWxAaG90bWFpbC5jb20iLCJpZCI6IjYzZDZjNmUyZDU2M2NmYWQ3YWJjOWQ0MCIsImlhdCI6MTY3NzQ5NDU1NH0.V6_Qvz9rbJUzme60VVRbZc6P2uRToRc8A9Na9N-5w94